### ISSUE TITLE
build failure with docker v25

### ISSUE THREAD

**Issue by hellt** [networkop/ignite#2]
Hi,
downstream users of your fork are flagging that the package fails to build once `container/common` has been bumped to `0.58.0`.

https://github.com/srl-labs/containerlab/pull/1937

This meta package introduced a bump for `github.com/docker/docker v25.0.3+incompatible` which I think might be actually the culprit here.

**Comment by networkop** [comment]
@hellt can you try the latest commit please?

**Comment by hellt** [comment]
Thanks @networkop 
can you debump docker to docker@v25.0.5+incompatible? Docker v26.0.0 is still very new and not all other deps in clab repo are compatible with the changes introduced there. Thanks

**Comment by networkop** [comment]
@hellt this should be done. Can you please check?

**Comment by hellt** [comment]
thanks @networkop 
all good now
