### ISSUE TITLE
udpate for docker 26+ and removing deprecated pullOptions

### ISSUE THREAD

**Issue by hellt** [networkop/ignite#3]
Hi @networkop 
would you mind bumping deps to docker v26 and clearing this error?

```
/pkg/runtime/docker/client.go:58:16: undefined: types.ImagePullOptions
```

The pull options are now in a separate package (`"github.com/docker/docker/api/types/image"`)

PS> you once already had docker at v26 - https://github.com/networkop/ignite/commit/02d1c784da52f151cd881df429eaaefc7c19943e

**Comment by networkop** [comment]
Will do once I'm back from pto

**Comment by networkop** [comment]
@hellt bumped the version, can you re-test please?

**Comment by hellt** [comment]
merci, all good now
